package com.gcu.user.bean;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.uCode
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    @TableId(type = IdType.AUTO)
    private Integer ucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.uName
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.uPwd
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    private String upwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.uType
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    private Integer utype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.uMemo
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    private String umemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.uCode
     *
     * @return the value of user_table.uCode
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public Integer getUcode() {
        return ucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.uCode
     *
     * @param ucode the value for user_table.uCode
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public void setUcode(Integer ucode) {
        this.ucode = ucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.uName
     *
     * @return the value of user_table.uName
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.uName
     *
     * @param uname the value for user_table.uName
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.uPwd
     *
     * @return the value of user_table.uPwd
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.uPwd
     *
     * @param upwd the value for user_table.uPwd
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.uType
     *
     * @return the value of user_table.uType
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public Integer getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.uType
     *
     * @param utype the value for user_table.uType
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public void setUtype(Integer utype) {
        this.utype = utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.uMemo
     *
     * @return the value of user_table.uMemo
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public String getUmemo() {
        return umemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.uMemo
     *
     * @param umemo the value for user_table.uMemo
     *
     * @mbggenerated Fri Sep 09 20:33:20 CST 2022
     */
    public void setUmemo(String umemo) {
        this.umemo = umemo == null ? null : umemo.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "ucode=" + ucode +
                ", uname='" + uname + '\'' +
                ", upwd='" + upwd + '\'' +
                ", utype=" + utype +
                ", umemo='" + umemo + '\'' +
                '}';
    }
}